---
- name: install EPEL repo
  yum: name=epel-release state=present

# tasks file for nginx
- name: Install the latest version of NGINX
  yum:
    name: nginx
    state: latest

- name: Copy nginx configuration
  template:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
